# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DefAcceleration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x44\x65\x66\x41\x63\x63\x65leration.proto\x12\x04vxII\"K\n\x13\x41\x63\x63\x65lerationSet4Way\x12\x0c\n\x04long\x18\x01 \x01(\x05\x12\x0b\n\x03lat\x18\x02 \x01(\x05\x12\x0c\n\x04vert\x18\x03 \x01(\x05\x12\x0b\n\x03yaw\x18\x04 \x01(\x05\x62\x06proto3')



_ACCELERATIONSET4WAY = DESCRIPTOR.message_types_by_name['AccelerationSet4Way']
AccelerationSet4Way = _reflection.GeneratedProtocolMessageType('AccelerationSet4Way', (_message.Message,), {
  'DESCRIPTOR' : _ACCELERATIONSET4WAY,
  '__module__' : 'DefAcceleration_pb2'
  # @@protoc_insertion_point(class_scope:vxII.AccelerationSet4Way)
  })
_sym_db.RegisterMessage(AccelerationSet4Way)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCELERATIONSET4WAY._serialized_start=31
  _ACCELERATIONSET4WAY._serialized_end=106
# @@protoc_insertion_point(module_scope)
