# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DefPosition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x44\x65\x66Position.proto\x12\x04vxII\x1a\x1egoogle/protobuf/wrappers.proto\"l\n\x15PositionConfidenceSet\x12%\n\x03pos\x18\x01 \x01(\x0e\x32\x18.vxII.PositionConfidence\x12,\n\televation\x18\x02 \x01(\x0e\x32\x19.vxII.ElevationConfidence\"W\n\nPosition3D\x12\x0b\n\x03lat\x18\x01 \x01(\x05\x12\x0c\n\x04long\x18\x02 \x01(\x05\x12.\n\televation\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\"O\n\x12PositionalAccuracy\x12\x11\n\tsemiMajor\x18\x01 \x01(\r\x12\x11\n\tsemiMinor\x18\x02 \x01(\r\x12\x13\n\x0borientation\x18\x03 \x01(\r*\xc2\x01\n\x12PositionConfidence\x12\x13\n\x0funavailable_pos\x10\x00\x12\t\n\x05\x61\x35\x30\x30m\x10\x01\x12\t\n\x05\x61\x32\x30\x30m\x10\x02\x12\t\n\x05\x61\x31\x30\x30m\x10\x03\x12\x08\n\x04\x61\x35\x30m\x10\x04\x12\x08\n\x04\x61\x32\x30m\x10\x05\x12\x08\n\x04\x61\x31\x30m\x10\x06\x12\x07\n\x03\x61\x35m\x10\x07\x12\x07\n\x03\x61\x32m\x10\x08\x12\x07\n\x03\x61\x31m\x10\t\x12\t\n\x05\x61\x35\x30\x63m\x10\n\x12\t\n\x05\x61\x32\x30\x63m\x10\x0b\x12\t\n\x05\x61\x31\x30\x63m\x10\x0c\x12\x08\n\x04\x61\x35\x63m\x10\r\x12\x08\n\x04\x61\x32\x63m\x10\x0e\x12\x08\n\x04\x61\x31\x63m\x10\x0f*\xab\x02\n\x13\x45levationConfidence\x12\x15\n\x11unavailable_elcfd\x10\x00\x12\x0f\n\x0b\x65lev_500_00\x10\x01\x12\x0f\n\x0b\x65lev_200_00\x10\x02\x12\x0f\n\x0b\x65lev_100_00\x10\x03\x12\x0f\n\x0b\x65lev_050_00\x10\x04\x12\x0f\n\x0b\x65lev_020_00\x10\x05\x12\x0f\n\x0b\x65lev_010_00\x10\x06\x12\x0f\n\x0b\x65lev_005_00\x10\x07\x12\x0f\n\x0b\x65lev_002_00\x10\x08\x12\x0f\n\x0b\x65lev_001_00\x10\t\x12\x0f\n\x0b\x65lev_000_50\x10\n\x12\x0f\n\x0b\x65lev_000_20\x10\x0b\x12\x0f\n\x0b\x65lev_000_10\x10\x0c\x12\x0f\n\x0b\x65lev_000_05\x10\r\x12\x0f\n\x0b\x65lev_000_02\x10\x0e\x12\x0f\n\x0b\x65lev_000_01\x10\x0f\x62\x06proto3')

_POSITIONCONFIDENCE = DESCRIPTOR.enum_types_by_name['PositionConfidence']
PositionConfidence = enum_type_wrapper.EnumTypeWrapper(_POSITIONCONFIDENCE)
_ELEVATIONCONFIDENCE = DESCRIPTOR.enum_types_by_name['ElevationConfidence']
ElevationConfidence = enum_type_wrapper.EnumTypeWrapper(_ELEVATIONCONFIDENCE)
unavailable_pos = 0
a500m = 1
a200m = 2
a100m = 3
a50m = 4
a20m = 5
a10m = 6
a5m = 7
a2m = 8
a1m = 9
a50cm = 10
a20cm = 11
a10cm = 12
a5cm = 13
a2cm = 14
a1cm = 15
unavailable_elcfd = 0
elev_500_00 = 1
elev_200_00 = 2
elev_100_00 = 3
elev_050_00 = 4
elev_020_00 = 5
elev_010_00 = 6
elev_005_00 = 7
elev_002_00 = 8
elev_001_00 = 9
elev_000_50 = 10
elev_000_20 = 11
elev_000_10 = 12
elev_000_05 = 13
elev_000_02 = 14
elev_000_01 = 15


_POSITIONCONFIDENCESET = DESCRIPTOR.message_types_by_name['PositionConfidenceSet']
_POSITION3D = DESCRIPTOR.message_types_by_name['Position3D']
_POSITIONALACCURACY = DESCRIPTOR.message_types_by_name['PositionalAccuracy']
PositionConfidenceSet = _reflection.GeneratedProtocolMessageType('PositionConfidenceSet', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONCONFIDENCESET,
  '__module__' : 'DefPosition_pb2'
  # @@protoc_insertion_point(class_scope:vxII.PositionConfidenceSet)
  })
_sym_db.RegisterMessage(PositionConfidenceSet)

Position3D = _reflection.GeneratedProtocolMessageType('Position3D', (_message.Message,), {
  'DESCRIPTOR' : _POSITION3D,
  '__module__' : 'DefPosition_pb2'
  # @@protoc_insertion_point(class_scope:vxII.Position3D)
  })
_sym_db.RegisterMessage(Position3D)

PositionalAccuracy = _reflection.GeneratedProtocolMessageType('PositionalAccuracy', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONALACCURACY,
  '__module__' : 'DefPosition_pb2'
  # @@protoc_insertion_point(class_scope:vxII.PositionalAccuracy)
  })
_sym_db.RegisterMessage(PositionalAccuracy)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSITIONCONFIDENCE._serialized_start=340
  _POSITIONCONFIDENCE._serialized_end=534
  _ELEVATIONCONFIDENCE._serialized_start=537
  _ELEVATIONCONFIDENCE._serialized_end=836
  _POSITIONCONFIDENCESET._serialized_start=59
  _POSITIONCONFIDENCESET._serialized_end=167
  _POSITION3D._serialized_start=169
  _POSITION3D._serialized_end=256
  _POSITIONALACCURACY._serialized_start=258
  _POSITIONALACCURACY._serialized_end=337
# @@protoc_insertion_point(module_scope)
