# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InjectObu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HV_pb2 as HV__pb2
import VIR_pb2 as VIR__pb2
import Platooning_pb2 as Platooning__pb2
import SensorSharing_pb2 as SensorSharing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fInjectObu.proto\x12\x04vxII\x1a\x08HV.proto\x1a\tVIR.proto\x1a\x10Platooning.proto\x1a\x13SensorSharing.proto\"\x90\x01\n\tInjectObu\x12\x18\n\x02hv\x18\x01 \x01(\x0b\x32\x0c.vxII.HvInfo\x12\x1e\n\x07iarData\x18\x02 \x01(\x0b\x32\r.vxII.IARData\x12$\n\nplatooning\x18\x03 \x01(\x0b\x32\x10.vxII.Platooning\x12#\n\x03ssm\x18\x04 \x01(\x0b\x32\x16.vxII.SensorSharingMsgb\x06proto3')



_INJECTOBU = DESCRIPTOR.message_types_by_name['InjectObu']
InjectObu = _reflection.GeneratedProtocolMessageType('InjectObu', (_message.Message,), {
  'DESCRIPTOR' : _INJECTOBU,
  '__module__' : 'InjectObu_pb2'
  # @@protoc_insertion_point(class_scope:vxII.InjectObu)
  })
_sym_db.RegisterMessage(InjectObu)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INJECTOBU._serialized_start=86
  _INJECTOBU._serialized_end=230
# @@protoc_insertion_point(module_scope)
