# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MapMatch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Map_pb2 as Map__pb2
import DefPosition_pb2 as DefPosition__pb2
import VxCommonDef_pb2 as VxCommonDef__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eMapMatch.proto\x12\x04vxII\x1a\tMap.proto\x1a\x11\x44\x65\x66Position.proto\x1a\x11VxCommonDef.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x98\x01\n\x11MmNodeReferenceID\x12\'\n\x08\x63urrNode\x18\x01 \x01(\x0b\x32\x15.vxII.NodeReferenceID\x12+\n\x0cupstreamNode\x18\x02 \x01(\x0b\x32\x15.vxII.NodeReferenceID\x12-\n\x0e\x64ownstreamNode\x18\x03 \x01(\x0b\x32\x15.vxII.NodeReferenceID\"Z\n\nMmLaneInfo\x12\x11\n\tcurLaneId\x18\x01 \x01(\x05\x12\x12\n\nleftLaneId\x18\x02 \x01(\x05\x12\x13\n\x0brightLaneId\x18\x03 \x01(\x05\x12\x10\n\x08rampFlag\x18\x04 \x01(\x08\"\xb7\x02\n\x08MapMatch\x12\x13\n\x0bmint1_of_ms\x18\x01 \x01(\r\x12&\n\x05refId\x18\x02 \x01(\x0b\x32\x17.vxII.MmNodeReferenceID\x12 \n\x06refPos\x18\x03 \x01(\x0b\x32\x10.vxII.Position3D\x12.\n\nspeedLimit\x18\x04 \x03(\x0b\x32\x1a.vxII.RegulatorySpeedLimit\x12$\n\nconnection\x18\x05 \x03(\x0b\x32\x10.vxII.Connection\x12!\n\tmovements\x18\x06 \x03(\x0b\x32\x0e.vxII.Movement\x12/\n\tmaneuvers\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12\"\n\x08laneInfo\x18\x08 \x01(\x0b\x32\x10.vxII.MmLaneInfob\x06proto3')



_MMNODEREFERENCEID = DESCRIPTOR.message_types_by_name['MmNodeReferenceID']
_MMLANEINFO = DESCRIPTOR.message_types_by_name['MmLaneInfo']
_MAPMATCH = DESCRIPTOR.message_types_by_name['MapMatch']
MmNodeReferenceID = _reflection.GeneratedProtocolMessageType('MmNodeReferenceID', (_message.Message,), {
  'DESCRIPTOR' : _MMNODEREFERENCEID,
  '__module__' : 'MapMatch_pb2'
  # @@protoc_insertion_point(class_scope:vxII.MmNodeReferenceID)
  })
_sym_db.RegisterMessage(MmNodeReferenceID)

MmLaneInfo = _reflection.GeneratedProtocolMessageType('MmLaneInfo', (_message.Message,), {
  'DESCRIPTOR' : _MMLANEINFO,
  '__module__' : 'MapMatch_pb2'
  # @@protoc_insertion_point(class_scope:vxII.MmLaneInfo)
  })
_sym_db.RegisterMessage(MmLaneInfo)

MapMatch = _reflection.GeneratedProtocolMessageType('MapMatch', (_message.Message,), {
  'DESCRIPTOR' : _MAPMATCH,
  '__module__' : 'MapMatch_pb2'
  # @@protoc_insertion_point(class_scope:vxII.MapMatch)
  })
_sym_db.RegisterMessage(MapMatch)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MMNODEREFERENCEID._serialized_start=106
  _MMNODEREFERENCEID._serialized_end=258
  _MMLANEINFO._serialized_start=260
  _MMLANEINFO._serialized_end=350
  _MAPMATCH._serialized_start=353
  _MAPMATCH._serialized_end=664
# @@protoc_insertion_point(module_scope)
