# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PAM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tPAM.proto\x12\x04vxII*\x8f\x02\n\x0bParkingType\x12\x18\n\x14unknown_parking_type\x10\x00\x12\x19\n\x15ordinary_parking_type\x10\x01\x12\x19\n\x15\x64isabled_parking_type\x10\x02\x12\x15\n\x11mini_parking_type\x10\x03\x12\x19\n\x15\x61ttached_parking_type\x10\x04\x12\x19\n\x15\x63harging_parking_type\x10\x05\x12\x17\n\x13stereo_parking_type\x10\x06\x12\x15\n\x11lady_parking_type\x10\x07\x12\x19\n\x15\x65xtended_parking_type\x10\x08\x12\x18\n\x14private_parking_type\x10\tb\x06proto3')

_PARKINGTYPE = DESCRIPTOR.enum_types_by_name['ParkingType']
ParkingType = enum_type_wrapper.EnumTypeWrapper(_PARKINGTYPE)
unknown_parking_type = 0
ordinary_parking_type = 1
disabled_parking_type = 2
mini_parking_type = 3
attached_parking_type = 4
charging_parking_type = 5
stereo_parking_type = 6
lady_parking_type = 7
extended_parking_type = 8
private_parking_type = 9


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARKINGTYPE._serialized_start=20
  _PARKINGTYPE._serialized_end=291
# @@protoc_insertion_point(module_scope)
