# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Platooning.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Platooning.proto\x12\x04vxII\":\n\nMemberNode\x12\x0b\n\x03vid\x18\x01 \x01(\t\x12\r\n\x05speed\x18\x02 \x01(\r\x12\x10\n\x08\x64istance\x18\x03 \x01(\r\"\xac\x01\n\x10MemberManagement\x12$\n\nmemberList\x18\x01 \x03(\x0b\x32\x10.vxII.MemberNode\x12%\n\x0bjoiningList\x18\x02 \x03(\x0b\x32\x10.vxII.MemberNode\x12%\n\x0bleavingList\x18\x03 \x03(\x0b\x32\x10.vxII.MemberNode\x12\x10\n\x08\x63\x61pacity\x18\x04 \x01(\r\x12\x12\n\nopenToJoin\x18\x05 \x01(\x08\"\x95\x01\n\nPlatooning\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12$\n\x04role\x18\x02 \x01(\x0e\x32\x16.vxII.RoleInPlatooning\x12(\n\x06status\x18\x03 \x01(\x0e\x32\x18.vxII.StatusInPlatooning\x12*\n\nleadingExt\x18\x04 \x01(\x0b\x32\x16.vxII.MemberManagement\"\xbd\x01\n\x05\x43LPMM\x12\x0e\n\x06msgCnt\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07secMark\x18\x03 \x01(\r\x12\x0b\n\x03pid\x18\x04 \x01(\t\x12$\n\x04role\x18\x05 \x01(\x0e\x32\x16.vxII.RoleInPlatooning\x12(\n\x06status\x18\x06 \x01(\x0e\x32\x18.vxII.StatusInPlatooning\x12*\n\nleadingExt\x18\x07 \x01(\x0b\x32\x16.vxII.MemberManagement*\x88\x01\n\x10RoleInPlatooning\x12\x1a\n\x16leader_role_platooning\x10\x00\x12\x1c\n\x18\x66ollower_role_platooning\x10\x01\x12\x18\n\x14tail_role_platooning\x10\x02\x12 \n\x1c\x66ree_vehicle_role_platooning\x10\x03*\x86\x02\n\x12StatusInPlatooning\x12 \n\x1cnavigating_status_platooning\x10\x00\x12%\n!beginToDissmiss_status_platooning\x10\x01\x12#\n\x1f\x61skForJoining_status_platooning\x10\x02\x12\x1d\n\x19joining_status_platooning\x10\x03\x12\x1f\n\x1b\x66ollowing_status_platooning\x10\x04\x12#\n\x1f\x61skForLeaving_status_platooning\x10\x05\x12\x1d\n\x19leaving_status_platooning\x10\x06\x62\x06proto3')

_ROLEINPLATOONING = DESCRIPTOR.enum_types_by_name['RoleInPlatooning']
RoleInPlatooning = enum_type_wrapper.EnumTypeWrapper(_ROLEINPLATOONING)
_STATUSINPLATOONING = DESCRIPTOR.enum_types_by_name['StatusInPlatooning']
StatusInPlatooning = enum_type_wrapper.EnumTypeWrapper(_STATUSINPLATOONING)
leader_role_platooning = 0
follower_role_platooning = 1
tail_role_platooning = 2
free_vehicle_role_platooning = 3
navigating_status_platooning = 0
beginToDissmiss_status_platooning = 1
askForJoining_status_platooning = 2
joining_status_platooning = 3
following_status_platooning = 4
askForLeaving_status_platooning = 5
leaving_status_platooning = 6


_MEMBERNODE = DESCRIPTOR.message_types_by_name['MemberNode']
_MEMBERMANAGEMENT = DESCRIPTOR.message_types_by_name['MemberManagement']
_PLATOONING = DESCRIPTOR.message_types_by_name['Platooning']
_CLPMM = DESCRIPTOR.message_types_by_name['CLPMM']
MemberNode = _reflection.GeneratedProtocolMessageType('MemberNode', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERNODE,
  '__module__' : 'Platooning_pb2'
  # @@protoc_insertion_point(class_scope:vxII.MemberNode)
  })
_sym_db.RegisterMessage(MemberNode)

MemberManagement = _reflection.GeneratedProtocolMessageType('MemberManagement', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERMANAGEMENT,
  '__module__' : 'Platooning_pb2'
  # @@protoc_insertion_point(class_scope:vxII.MemberManagement)
  })
_sym_db.RegisterMessage(MemberManagement)

Platooning = _reflection.GeneratedProtocolMessageType('Platooning', (_message.Message,), {
  'DESCRIPTOR' : _PLATOONING,
  '__module__' : 'Platooning_pb2'
  # @@protoc_insertion_point(class_scope:vxII.Platooning)
  })
_sym_db.RegisterMessage(Platooning)

CLPMM = _reflection.GeneratedProtocolMessageType('CLPMM', (_message.Message,), {
  'DESCRIPTOR' : _CLPMM,
  '__module__' : 'Platooning_pb2'
  # @@protoc_insertion_point(class_scope:vxII.CLPMM)
  })
_sym_db.RegisterMessage(CLPMM)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLEINPLATOONING._serialized_start=606
  _ROLEINPLATOONING._serialized_end=742
  _STATUSINPLATOONING._serialized_start=745
  _STATUSINPLATOONING._serialized_end=1007
  _MEMBERNODE._serialized_start=26
  _MEMBERNODE._serialized_end=84
  _MEMBERMANAGEMENT._serialized_start=87
  _MEMBERMANAGEMENT._serialized_end=259
  _PLATOONING._serialized_start=262
  _PLATOONING._serialized_end=411
  _CLPMM._serialized_start=414
  _CLPMM._serialized_end=603
# @@protoc_insertion_point(module_scope)
