# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VehEmgExt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fVehEmgExt.proto\x12\x04vxII\"\x92\x01\n\x1aVehicleEmergencyExtensions\x12(\n\x0cresponseType\x18\x01 \x01(\x0e\x32\x12.vxII.ResponseType\x12\"\n\x08sirenUse\x18\x02 \x01(\x0e\x32\x10.vxII.SirenInUse\x12&\n\tlightsUse\x18\x03 \x01(\x0e\x32\x13.vxII.LightbarInUse*\xf0\x01\n\x0cResponseType\x12\'\n#notInUseOrNotEquipped_response_type\x10\x00\x12\x1b\n\x17\x65mergency_response_type\x10\x01\x12\x1e\n\x1anonEmergency_response_type\x10\x02\x12\x19\n\x15pursuit_response_type\x10\x03\x12\x1c\n\x18stationary_response_type\x10\x04\x12\x1c\n\x18slowMoving_response_type\x10\x05\x12#\n\x1fstopAndGoMovement_response_type\x10\x06*t\n\nSirenInUse\x12\x1b\n\x17unavailable_siren_inuse\x10\x00\x12\x18\n\x14notInUse_siren_inuse\x10\x01\x12\x15\n\x11inUse_siren_inuse\x10\x02\x12\x18\n\x14reserved_siren_inuse\x10\x03*\xa4\x02\n\rLightbarInUse\x12\x1f\n\x1bunavailable_light_bar_inuse\x10\x00\x12\x1c\n\x18notInUse_light_bar_inuse\x10\x01\x12\x19\n\x15inUse_light_bar_inuse\x10\x02\x12\'\n#yellowCautionLights_light_bar_inuse\x10\x03\x12$\n schooldBusLights_light_bar_inuse\x10\x04\x12$\n arrowSignsActive_light_bar_inuse\x10\x05\x12%\n!slowMovingVehicle_light_bar_inuse\x10\x06\x12\x1d\n\x19\x66reqStops_light_bar_inuse\x10\x07\x62\x06proto3')

_RESPONSETYPE = DESCRIPTOR.enum_types_by_name['ResponseType']
ResponseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
_SIRENINUSE = DESCRIPTOR.enum_types_by_name['SirenInUse']
SirenInUse = enum_type_wrapper.EnumTypeWrapper(_SIRENINUSE)
_LIGHTBARINUSE = DESCRIPTOR.enum_types_by_name['LightbarInUse']
LightbarInUse = enum_type_wrapper.EnumTypeWrapper(_LIGHTBARINUSE)
notInUseOrNotEquipped_response_type = 0
emergency_response_type = 1
nonEmergency_response_type = 2
pursuit_response_type = 3
stationary_response_type = 4
slowMoving_response_type = 5
stopAndGoMovement_response_type = 6
unavailable_siren_inuse = 0
notInUse_siren_inuse = 1
inUse_siren_inuse = 2
reserved_siren_inuse = 3
unavailable_light_bar_inuse = 0
notInUse_light_bar_inuse = 1
inUse_light_bar_inuse = 2
yellowCautionLights_light_bar_inuse = 3
schooldBusLights_light_bar_inuse = 4
arrowSignsActive_light_bar_inuse = 5
slowMovingVehicle_light_bar_inuse = 6
freqStops_light_bar_inuse = 7


_VEHICLEEMERGENCYEXTENSIONS = DESCRIPTOR.message_types_by_name['VehicleEmergencyExtensions']
VehicleEmergencyExtensions = _reflection.GeneratedProtocolMessageType('VehicleEmergencyExtensions', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLEEMERGENCYEXTENSIONS,
  '__module__' : 'VehEmgExt_pb2'
  # @@protoc_insertion_point(class_scope:vxII.VehicleEmergencyExtensions)
  })
_sym_db.RegisterMessage(VehicleEmergencyExtensions)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSETYPE._serialized_start=175
  _RESPONSETYPE._serialized_end=415
  _SIRENINUSE._serialized_start=417
  _SIRENINUSE._serialized_end=533
  _LIGHTBARINUSE._serialized_start=536
  _LIGHTBARINUSE._serialized_end=828
  _VEHICLEEMERGENCYEXTENSIONS._serialized_start=26
  _VEHICLEEMERGENCYEXTENSIONS._serialized_end=172
# @@protoc_insertion_point(module_scope)
