# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VehSize.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rVehSize.proto\x12\x04vxII\"A\n\x07VehSize\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x10\n\x06height\x18\x03 \x01(\x05H\x00\x42\x05\n\x03hgtb\x06proto3')



_VEHSIZE = DESCRIPTOR.message_types_by_name['VehSize']
VehSize = _reflection.GeneratedProtocolMessageType('VehSize', (_message.Message,), {
  'DESCRIPTOR' : _VEHSIZE,
  '__module__' : 'VehSize_pb2'
  # @@protoc_insertion_point(class_scope:vxII.VehSize)
  })
_sym_db.RegisterMessage(VehSize)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHSIZE._serialized_start=23
  _VEHSIZE._serialized_end=88
# @@protoc_insertion_point(module_scope)
