# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VehStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fVehStatus.proto\x12\x04vxII*\x98\x01\n\x11TransmissionState\x12\x0b\n\x07neutral\x10\x00\x12\x08\n\x04park\x10\x01\x12\x10\n\x0c\x66orwardGears\x10\x02\x12\x10\n\x0creverseGears\x10\x03\x12\r\n\treserved1\x10\x04\x12\r\n\treserved2\x10\x05\x12\r\n\treserved3\x10\x06\x12\x1b\n\x17unavailable_trans_state\x10\x07*\xde\x02\n\x11VehicleEventFlags\x12\x15\n\x11\x65ventHazardLights\x10\x00\x12\x1a\n\x16\x65ventStopLineViolation\x10\x01\x12\x15\n\x11\x65ventABSactivated\x10\x02\x12\x1c\n\x18\x65ventTractionControlLoss\x10\x03\x12\"\n\x1e\x65ventStabilityControlactivated\x10\x04\x12\x1b\n\x17\x65ventHazardousMaterials\x10\x05\x12\x12\n\x0e\x65ventReserved1\x10\x06\x12\x14\n\x10\x65ventHardBraking\x10\x07\x12\x16\n\x12\x65ventLightsChanged\x10\x08\x12\x16\n\x12\x65ventWipersChanged\x10\t\x12\x11\n\reventFlatTire\x10\n\x12\x18\n\x14\x65ventDisabledVehicle\x10\x0b\x12\x19\n\x15\x65ventAirBagDeployment\x10\x0c*\xe2\x01\n\x0e\x45xteriorLights\x12\x17\n\x13lowBeamHeadlightsOn\x10\x00\x12\x18\n\x14highBeamHeadlightsOn\x10\x01\x12\x14\n\x10leftTurnSignalOn\x10\x02\x12\x15\n\x11rightTurnSignalOn\x10\x03\x12\x12\n\x0ehazardSignalOn\x10\x04\x12\x1b\n\x17\x61utomaticLightControlOn\x10\x05\x12\x1a\n\x16\x64\x61ytimeRunningLightsOn\x10\x06\x12\x0e\n\nfogLightOn\x10\x07\x12\x13\n\x0fparkingLightsOn\x10\x08\x62\x06proto3')

_TRANSMISSIONSTATE = DESCRIPTOR.enum_types_by_name['TransmissionState']
TransmissionState = enum_type_wrapper.EnumTypeWrapper(_TRANSMISSIONSTATE)
_VEHICLEEVENTFLAGS = DESCRIPTOR.enum_types_by_name['VehicleEventFlags']
VehicleEventFlags = enum_type_wrapper.EnumTypeWrapper(_VEHICLEEVENTFLAGS)
_EXTERIORLIGHTS = DESCRIPTOR.enum_types_by_name['ExteriorLights']
ExteriorLights = enum_type_wrapper.EnumTypeWrapper(_EXTERIORLIGHTS)
neutral = 0
park = 1
forwardGears = 2
reverseGears = 3
reserved1 = 4
reserved2 = 5
reserved3 = 6
unavailable_trans_state = 7
eventHazardLights = 0
eventStopLineViolation = 1
eventABSactivated = 2
eventTractionControlLoss = 3
eventStabilityControlactivated = 4
eventHazardousMaterials = 5
eventReserved1 = 6
eventHardBraking = 7
eventLightsChanged = 8
eventWipersChanged = 9
eventFlatTire = 10
eventDisabledVehicle = 11
eventAirBagDeployment = 12
lowBeamHeadlightsOn = 0
highBeamHeadlightsOn = 1
leftTurnSignalOn = 2
rightTurnSignalOn = 3
hazardSignalOn = 4
automaticLightControlOn = 5
daytimeRunningLightsOn = 6
fogLightOn = 7
parkingLightsOn = 8


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSMISSIONSTATE._serialized_start=26
  _TRANSMISSIONSTATE._serialized_end=178
  _VEHICLEEVENTFLAGS._serialized_start=181
  _VEHICLEEVENTFLAGS._serialized_end=531
  _EXTERIORLIGHTS._serialized_start=534
  _EXTERIORLIGHTS._serialized_end=760
# @@protoc_insertion_point(module_scope)
