# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VxCommonDef.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11VxCommonDef.proto\x12\x04vxII\x1a\x1egoogle/protobuf/wrappers.proto\"-\n\x0fNodeReferenceID\x12\x0e\n\x06region\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\r\"I\n\x14RegulatorySpeedLimit\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.vxII.SpeedLimitType\x12\r\n\x05speed\x18\x02 \x01(\r\"\x96\x01\n\nMovementEx\x12\x31\n\x12remoteIntersection\x18\x01 \x01(\x0b\x32\x15.vxII.NodeReferenceID\x12-\n\x07phaseId\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12&\n\x0eturn_direction\x18\x03 \x01(\x0e\x32\x0e.vxII.Maneuver*\x85\x03\n\x0eSpeedLimitType\x12\x1c\n\x18unknown_speed_limit_type\x10\x00\x12\x18\n\x14maxSpeedInSchoolZone\x10\x01\x12.\n*maxSpeedInSchoolZoneWhenChildrenArePresent\x10\x02\x12\x1e\n\x1amaxSpeedInConstructionZone\x10\x03\x12\x13\n\x0fvehicleMinSpeed\x10\x04\x12\x13\n\x0fvehicleMaxSpeed\x10\x05\x12\x18\n\x14vehicleNightMaxSpeed\x10\x06\x12\x11\n\rtruckMinSpeed\x10\x07\x12\x11\n\rtruckMaxSpeed\x10\x08\x12\x16\n\x12truckNightMaxSpeed\x10\t\x12 \n\x1cvehiclesWithTrailersMinSpeed\x10\n\x12 \n\x1cvehiclesWithTrailersMaxSpeed\x10\x0b\x12%\n!vehiclesWithTrailersNightMaxSpeed\x10\x0c*\x84\x01\n\x08Maneuver\x12\x1d\n\x19maneuverStraight_maneuver\x10\x00\x12\x1d\n\x19maneuverLeftTurn_maneuver\x10\x01\x12\x1e\n\x1amaneuverRightTurn_maneuver\x10\x02\x12\x1a\n\x16maneuverUTurn_maneuver\x10\x03\x62\x06proto3')

_SPEEDLIMITTYPE = DESCRIPTOR.enum_types_by_name['SpeedLimitType']
SpeedLimitType = enum_type_wrapper.EnumTypeWrapper(_SPEEDLIMITTYPE)
_MANEUVER = DESCRIPTOR.enum_types_by_name['Maneuver']
Maneuver = enum_type_wrapper.EnumTypeWrapper(_MANEUVER)
unknown_speed_limit_type = 0
maxSpeedInSchoolZone = 1
maxSpeedInSchoolZoneWhenChildrenArePresent = 2
maxSpeedInConstructionZone = 3
vehicleMinSpeed = 4
vehicleMaxSpeed = 5
vehicleNightMaxSpeed = 6
truckMinSpeed = 7
truckMaxSpeed = 8
truckNightMaxSpeed = 9
vehiclesWithTrailersMinSpeed = 10
vehiclesWithTrailersMaxSpeed = 11
vehiclesWithTrailersNightMaxSpeed = 12
maneuverStraight_maneuver = 0
maneuverLeftTurn_maneuver = 1
maneuverRightTurn_maneuver = 2
maneuverUTurn_maneuver = 3


_NODEREFERENCEID = DESCRIPTOR.message_types_by_name['NodeReferenceID']
_REGULATORYSPEEDLIMIT = DESCRIPTOR.message_types_by_name['RegulatorySpeedLimit']
_MOVEMENTEX = DESCRIPTOR.message_types_by_name['MovementEx']
NodeReferenceID = _reflection.GeneratedProtocolMessageType('NodeReferenceID', (_message.Message,), {
  'DESCRIPTOR' : _NODEREFERENCEID,
  '__module__' : 'VxCommonDef_pb2'
  # @@protoc_insertion_point(class_scope:vxII.NodeReferenceID)
  })
_sym_db.RegisterMessage(NodeReferenceID)

RegulatorySpeedLimit = _reflection.GeneratedProtocolMessageType('RegulatorySpeedLimit', (_message.Message,), {
  'DESCRIPTOR' : _REGULATORYSPEEDLIMIT,
  '__module__' : 'VxCommonDef_pb2'
  # @@protoc_insertion_point(class_scope:vxII.RegulatorySpeedLimit)
  })
_sym_db.RegisterMessage(RegulatorySpeedLimit)

MovementEx = _reflection.GeneratedProtocolMessageType('MovementEx', (_message.Message,), {
  'DESCRIPTOR' : _MOVEMENTEX,
  '__module__' : 'VxCommonDef_pb2'
  # @@protoc_insertion_point(class_scope:vxII.MovementEx)
  })
_sym_db.RegisterMessage(MovementEx)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPEEDLIMITTYPE._serialized_start=335
  _SPEEDLIMITTYPE._serialized_end=724
  _MANEUVER._serialized_start=727
  _MANEUVER._serialized_end=859
  _NODEREFERENCEID._serialized_start=59
  _NODEREFERENCEID._serialized_end=104
  _REGULATORYSPEEDLIMIT._serialized_start=106
  _REGULATORYSPEEDLIMIT._serialized_end=179
  _MOVEMENTEX._serialized_start=182
  _MOVEMENTEX._serialized_end=332
# @@protoc_insertion_point(module_scope)
