# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BSM.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DefTime_pb2 as DefTime__pb2
import VehSize_pb2 as VehSize__pb2
import VehClass_pb2 as VehClass__pb2
import VehBrake_pb2 as VehBrake__pb2
import VehStatus_pb2 as VehStatus__pb2
import DefMotion_pb2 as DefMotion__pb2
import VehEmgExt_pb2 as VehEmgExt__pb2
import DefPosition_pb2 as DefPosition__pb2
import VehSafetyExt_pb2 as VehSafetyExt__pb2
import DefAcceleration_pb2 as DefAcceleration__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tBSM.proto\x12\x04vxII\x1a\rDefTime.proto\x1a\rVehSize.proto\x1a\x0eVehClass.proto\x1a\x0eVehBrake.proto\x1a\x0fVehStatus.proto\x1a\x0f\x44\x65\x66Motion.proto\x1a\x0fVehEmgExt.proto\x1a\x11\x44\x65\x66Position.proto\x1a\x12VehSafetyExt.proto\x1a\x15\x44\x65\x66\x41\x63\x63\x65leration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9b\x05\n\x03\x42SM\x12\x0e\n\x06msgCnt\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07secMark\x18\x03 \x01(\r\x12,\n\x0etimeConfidence\x18\x04 \x01(\x0e\x32\x14.vxII.TimeConfidence\x12\x1d\n\x03pos\x18\x05 \x01(\x0b\x32\x10.vxII.Position3D\x12-\n\x0bposAccuracy\x18\x06 \x01(\x0b\x32\x18.vxII.PositionalAccuracy\x12\x32\n\rposConfidence\x18\x07 \x01(\x0b\x32\x1b.vxII.PositionConfidenceSet\x12-\n\x0ctransmission\x18\x08 \x01(\x0e\x32\x17.vxII.TransmissionState\x12\r\n\x05speed\x18\t \x01(\r\x12\x0f\n\x07heading\x18\n \x01(\r\x12*\n\x05\x61ngle\x18\x0b \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12,\n\tmotionCfd\x18\x0c \x01(\x0b\x32\x19.vxII.MotionConfidenceSet\x12+\n\x08\x61\x63\x63\x65lSet\x18\r \x01(\x0b\x32\x19.vxII.AccelerationSet4Way\x12\'\n\x06\x62rakes\x18\x0e \x01(\x0b\x32\x17.vxII.BrakeSystemStatus\x12\x1b\n\x04size\x18\x0f \x01(\x0b\x32\r.vxII.VehSize\x12\x31\n\x0cvehicleClass\x18\x10 \x01(\x0b\x32\x1b.vxII.VehicleClassification\x12\x30\n\tsafetyExt\x18\x11 \x01(\x0b\x32\x1d.vxII.VehicleSafetyExtensions\x12\x36\n\x0c\x65mergencyExt\x18\x12 \x01(\x0b\x32 .vxII.VehicleEmergencyExtensionsb\x06proto3')



_BSM = DESCRIPTOR.message_types_by_name['BSM']
BSM = _reflection.GeneratedProtocolMessageType('BSM', (_message.Message,), {
  'DESCRIPTOR' : _BSM,
  '__module__' : 'BSM_pb2'
  # @@protoc_insertion_point(class_scope:vxII.BSM)
  })
_sym_db.RegisterMessage(BSM)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BSM._serialized_start=227
  _BSM._serialized_end=894
# @@protoc_insertion_point(module_scope)
