# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Cooperative.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DefPosition_pb2 as DefPosition__pb2
import Participant_pb2 as Participant__pb2
import SensorSharing_pb2 as SensorSharing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43ooperative.proto\x12\x04vxII\x1a\x11\x44\x65\x66Position.proto\x1a\x11Participant.proto\x1a\x13SensorSharing.proto\"B\n\x15\x43ooperativeLaneChange\x12)\n\nsuggestion\x18\x01 \x01(\x0e\x32\x15.vxII.DriveSuggestion\"X\n\x13\x43ooperativeVehMerge\x12)\n\nsuggestion\x18\x01 \x01(\x0e\x32\x15.vxII.DriveSuggestion\x12\x16\n\x0emerge_end_dist\x18\x02 \x01(\r\"\x98\x01\n\x1e\x43ooperativeHighPriorityPassing\x12\x1b\n\x13\x63urrent_lane_status\x18\x01 \x01(\x08\x12)\n\nsuggestion\x18\x02 \x01(\x0e\x32\x15.vxII.DriveSuggestion\x12\x1d\n\x02rv\x18\x03 \x01(\x0b\x32\x11.vxII.Participant\x12\x0f\n\x07rv_dist\x18\x04 \x01(\r\"\xfd\x01\n\x1b\x43ooperativeSharingSensorMsg\x12\x30\n\x0f\x64\x65tectedPTCType\x18\x01 \x01(\x0e\x32\x15.vxII.DetectedPTCTypeH\x00\x12%\n\x07obsType\x18\x02 \x01(\x0e\x32\x12.vxII.ObstacleTypeH\x00\x12\r\n\x05obsId\x18\x03 \x01(\r\x12\x0f\n\x07secMark\x18\x04 \x01(\r\x12\x1d\n\x03pos\x18\x05 \x01(\x0b\x32\x10.vxII.Position3D\x12\r\n\x05speed\x18\x06 \x01(\r\x12\x0f\n\x07heading\x18\x07 \x01(\r\x12\x1e\n\x04size\x18\x08 \x01(\x0b\x32\x10.vxII.ObjectSizeB\x06\n\x04type*\xe8\x03\n\x0f\x44riveSuggestion\x12#\n\x1f\x44riveBehavior_goStraightForward\x10\x00\x12$\n DriveBehavior_laneChangingToLeft\x10\x01\x12%\n!DriveBehavior_laneChangingToRight\x10\x02\x12\x18\n\x14\x44riveBehavior_rampIn\x10\x03\x12\x19\n\x15\x44riveBehavior_rampOut\x10\x04\x12-\n)DriveBehavior_intersectionStraightThrough\x10\x05\x12&\n\"DriveBehavior_intersectionTurnLeft\x10\x06\x12\'\n#DriveBehavior_intersectionTurnRight\x10\x07\x12#\n\x1f\x44riveBehavior_intersectionUTurn\x10\x08\x12\x1d\n\x19\x44riveBehavior_stop_and_go\x10\t\x12\x16\n\x12\x44riveBehavior_stop\x10\n\x12\x1b\n\x17\x44riveBehavior_slow_down\x10\x0b\x12\x1a\n\x16\x44riveBehavior_speed_up\x10\x0c\x12\x19\n\x15\x44riveBehavior_parking\x10\rb\x06proto3')

_DRIVESUGGESTION = DESCRIPTOR.enum_types_by_name['DriveSuggestion']
DriveSuggestion = enum_type_wrapper.EnumTypeWrapper(_DRIVESUGGESTION)
DriveBehavior_goStraightForward = 0
DriveBehavior_laneChangingToLeft = 1
DriveBehavior_laneChangingToRight = 2
DriveBehavior_rampIn = 3
DriveBehavior_rampOut = 4
DriveBehavior_intersectionStraightThrough = 5
DriveBehavior_intersectionTurnLeft = 6
DriveBehavior_intersectionTurnRight = 7
DriveBehavior_intersectionUTurn = 8
DriveBehavior_stop_and_go = 9
DriveBehavior_stop = 10
DriveBehavior_slow_down = 11
DriveBehavior_speed_up = 12
DriveBehavior_parking = 13


_COOPERATIVELANECHANGE = DESCRIPTOR.message_types_by_name['CooperativeLaneChange']
_COOPERATIVEVEHMERGE = DESCRIPTOR.message_types_by_name['CooperativeVehMerge']
_COOPERATIVEHIGHPRIORITYPASSING = DESCRIPTOR.message_types_by_name['CooperativeHighPriorityPassing']
_COOPERATIVESHARINGSENSORMSG = DESCRIPTOR.message_types_by_name['CooperativeSharingSensorMsg']
CooperativeLaneChange = _reflection.GeneratedProtocolMessageType('CooperativeLaneChange', (_message.Message,), {
  'DESCRIPTOR' : _COOPERATIVELANECHANGE,
  '__module__' : 'Cooperative_pb2'
  # @@protoc_insertion_point(class_scope:vxII.CooperativeLaneChange)
  })
_sym_db.RegisterMessage(CooperativeLaneChange)

CooperativeVehMerge = _reflection.GeneratedProtocolMessageType('CooperativeVehMerge', (_message.Message,), {
  'DESCRIPTOR' : _COOPERATIVEVEHMERGE,
  '__module__' : 'Cooperative_pb2'
  # @@protoc_insertion_point(class_scope:vxII.CooperativeVehMerge)
  })
_sym_db.RegisterMessage(CooperativeVehMerge)

CooperativeHighPriorityPassing = _reflection.GeneratedProtocolMessageType('CooperativeHighPriorityPassing', (_message.Message,), {
  'DESCRIPTOR' : _COOPERATIVEHIGHPRIORITYPASSING,
  '__module__' : 'Cooperative_pb2'
  # @@protoc_insertion_point(class_scope:vxII.CooperativeHighPriorityPassing)
  })
_sym_db.RegisterMessage(CooperativeHighPriorityPassing)

CooperativeSharingSensorMsg = _reflection.GeneratedProtocolMessageType('CooperativeSharingSensorMsg', (_message.Message,), {
  'DESCRIPTOR' : _COOPERATIVESHARINGSENSORMSG,
  '__module__' : 'Cooperative_pb2'
  # @@protoc_insertion_point(class_scope:vxII.CooperativeSharingSensorMsg)
  })
_sym_db.RegisterMessage(CooperativeSharingSensorMsg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRIVESUGGESTION._serialized_start=656
  _DRIVESUGGESTION._serialized_end=1144
  _COOPERATIVELANECHANGE._serialized_start=86
  _COOPERATIVELANECHANGE._serialized_end=152
  _COOPERATIVEVEHMERGE._serialized_start=154
  _COOPERATIVEVEHMERGE._serialized_end=242
  _COOPERATIVEHIGHPRIORITYPASSING._serialized_start=245
  _COOPERATIVEHIGHPRIORITYPASSING._serialized_end=397
  _COOPERATIVESHARINGSENSORMSG._serialized_start=400
  _COOPERATIVESHARINGSENSORMSG._serialized_end=653
# @@protoc_insertion_point(module_scope)
