# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DefMotion.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x44\x65\x66Motion.proto\x12\x04vxII\"\xa1\x01\n\x13MotionConfidenceSet\x12\'\n\x08speedCfd\x18\x01 \x01(\x0e\x32\x15.vxII.SpeedConfidence\x12+\n\nheadingCfd\x18\x02 \x01(\x0e\x32\x17.vxII.HeadingConfidence\x12\x34\n\x08steerCfd\x18\x03 \x01(\x0e\x32\".vxII.SteeringWheelAngleConfidence*\xf7\x01\n\x11HeadingConfidence\x12\x1b\n\x17unavailable_heading_cfd\x10\x00\x12\x19\n\x15prec10deg_heading_cfd\x10\x01\x12\x19\n\x15prec05deg_heading_cfd\x10\x02\x12\x1a\n\x16prec01deg_heading_cfd1\x10\x03\x12\x1a\n\x16prec0_1deg_heading_cfd\x10\x04\x12\x1b\n\x17prec0_05deg_heading_cfd\x10\x05\x12\x1b\n\x17prec0_01deg_heading_cfd\x10\x06\x12\x1d\n\x19prec0_0125deg_heading_cfd\x10\x07*\xd8\x01\n\x0fSpeedConfidence\x12\x19\n\x15unavailable_speed_cfd\x10\x00\x12\x17\n\x13prec100ms_speed_cfd\x10\x01\x12\x16\n\x12prec10ms_speed_cfd\x10\x02\x12\x15\n\x11prec5ms_speed_cfd\x10\x03\x12\x15\n\x11prec1ms_speed_cfd\x10\x04\x12\x17\n\x13prec0_1ms_speed_cfd\x10\x05\x12\x18\n\x14prec0_05ms_speed_cfd\x10\x06\x12\x18\n\x14prec0_01ms_speed_cfd\x10\x07*\xb4\x01\n\x1cSteeringWheelAngleConfidence\x12%\n!unavailable_steer_wheel_angle_cfd\x10\x00\x12\"\n\x1eprec2deg_steer_wheel_angle_cfd\x10\x01\x12\"\n\x1eprec1deg_steer_wheel_angle_cfd\x10\x02\x12%\n!prec0_02deg_steer_wheel_angle_cfd\x10\x03\x62\x06proto3')

_HEADINGCONFIDENCE = DESCRIPTOR.enum_types_by_name['HeadingConfidence']
HeadingConfidence = enum_type_wrapper.EnumTypeWrapper(_HEADINGCONFIDENCE)
_SPEEDCONFIDENCE = DESCRIPTOR.enum_types_by_name['SpeedConfidence']
SpeedConfidence = enum_type_wrapper.EnumTypeWrapper(_SPEEDCONFIDENCE)
_STEERINGWHEELANGLECONFIDENCE = DESCRIPTOR.enum_types_by_name['SteeringWheelAngleConfidence']
SteeringWheelAngleConfidence = enum_type_wrapper.EnumTypeWrapper(_STEERINGWHEELANGLECONFIDENCE)
unavailable_heading_cfd = 0
prec10deg_heading_cfd = 1
prec05deg_heading_cfd = 2
prec01deg_heading_cfd1 = 3
prec0_1deg_heading_cfd = 4
prec0_05deg_heading_cfd = 5
prec0_01deg_heading_cfd = 6
prec0_0125deg_heading_cfd = 7
unavailable_speed_cfd = 0
prec100ms_speed_cfd = 1
prec10ms_speed_cfd = 2
prec5ms_speed_cfd = 3
prec1ms_speed_cfd = 4
prec0_1ms_speed_cfd = 5
prec0_05ms_speed_cfd = 6
prec0_01ms_speed_cfd = 7
unavailable_steer_wheel_angle_cfd = 0
prec2deg_steer_wheel_angle_cfd = 1
prec1deg_steer_wheel_angle_cfd = 2
prec0_02deg_steer_wheel_angle_cfd = 3


_MOTIONCONFIDENCESET = DESCRIPTOR.message_types_by_name['MotionConfidenceSet']
MotionConfidenceSet = _reflection.GeneratedProtocolMessageType('MotionConfidenceSet', (_message.Message,), {
  'DESCRIPTOR' : _MOTIONCONFIDENCESET,
  '__module__' : 'DefMotion_pb2'
  # @@protoc_insertion_point(class_scope:vxII.MotionConfidenceSet)
  })
_sym_db.RegisterMessage(MotionConfidenceSet)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADINGCONFIDENCE._serialized_start=190
  _HEADINGCONFIDENCE._serialized_end=437
  _SPEEDCONFIDENCE._serialized_start=440
  _SPEEDCONFIDENCE._serialized_end=656
  _STEERINGWHEELANGLECONFIDENCE._serialized_start=659
  _STEERINGWHEELANGLECONFIDENCE._serialized_end=839
  _MOTIONCONFIDENCESET._serialized_start=26
  _MOTIONCONFIDENCESET._serialized_end=187
# @@protoc_insertion_point(module_scope)
