# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ObuApp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Map_pb2 as Map__pb2
import VehSetting_pb2 as VehSetting__pb2
import Participant_pb2 as Participant__pb2
import TargetAlert_pb2 as TargetAlert__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cObuApp.proto\x12\x04vxII\x1a\tMap.proto\x1a\x10VehSetting.proto\x1a\x11Participant.proto\x1a\x11TargetAlert.proto\",\n\nObuAppResp\x12\x0e\n\x06msgCnt\x18\x01 \x01(\r\x12\x0e\n\x06retVal\x18\x02 \x01(\x05\"&\n\nObuAppInfo\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\n\n\x02id\x18\x02 \x01(\t\"\xf8\x01\n\x06ObuApp\x12\x1f\n\x02hv\x18\x01 \x01(\x0b\x32\x11.vxII.ParticipantH\x00\x12!\n\x03rvs\x18\x02 \x01(\x0b\x32\x12.vxII.ParticipantsH\x00\x12\x18\n\x03map\x18\x05 \x01(\x0b\x32\t.vxII.MapH\x00\x12\"\n\x05\x61lert\x18\t \x01(\x0b\x32\x11.vxII.TargetAlertH\x00\x12#\n\x07setting\x18\n \x01(\x0b\x32\x10.vxII.VehSettingH\x00\x12 \n\x04resp\x18\x0b \x01(\x0b\x32\x10.vxII.ObuAppRespH\x00\x12\x1e\n\x04info\x18\x0c \x01(\x0b\x32\x10.vxII.ObuAppInfoB\x05\n\x03msgb\x06proto3')



_OBUAPPRESP = DESCRIPTOR.message_types_by_name['ObuAppResp']
_OBUAPPINFO = DESCRIPTOR.message_types_by_name['ObuAppInfo']
_OBUAPP = DESCRIPTOR.message_types_by_name['ObuApp']
ObuAppResp = _reflection.GeneratedProtocolMessageType('ObuAppResp', (_message.Message,), {
  'DESCRIPTOR' : _OBUAPPRESP,
  '__module__' : 'ObuApp_pb2'
  # @@protoc_insertion_point(class_scope:vxII.ObuAppResp)
  })
_sym_db.RegisterMessage(ObuAppResp)

ObuAppInfo = _reflection.GeneratedProtocolMessageType('ObuAppInfo', (_message.Message,), {
  'DESCRIPTOR' : _OBUAPPINFO,
  '__module__' : 'ObuApp_pb2'
  # @@protoc_insertion_point(class_scope:vxII.ObuAppInfo)
  })
_sym_db.RegisterMessage(ObuAppInfo)

ObuApp = _reflection.GeneratedProtocolMessageType('ObuApp', (_message.Message,), {
  'DESCRIPTOR' : _OBUAPP,
  '__module__' : 'ObuApp_pb2'
  # @@protoc_insertion_point(class_scope:vxII.ObuApp)
  })
_sym_db.RegisterMessage(ObuApp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBUAPPRESP._serialized_start=89
  _OBUAPPRESP._serialized_end=133
  _OBUAPPINFO._serialized_start=135
  _OBUAPPINFO._serialized_end=173
  _OBUAPP._serialized_start=176
  _OBUAPP._serialized_end=424
# @@protoc_insertion_point(module_scope)
