# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Participant.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VehSize_pb2 as VehSize__pb2
import VehClass_pb2 as VehClass__pb2
import VehBrake_pb2 as VehBrake__pb2
import DefPosition_pb2 as DefPosition__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Participant.proto\x12\x04vxII\x1a\rVehSize.proto\x1a\x0eVehClass.proto\x1a\x0eVehBrake.proto\x1a\x11\x44\x65\x66Position.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb7\x02\n\x0bParticipant\x12\x0e\n\x06msgCnt\x18\x01 \x01(\r\x12\n\n\x02id\x18\x03 \x01(\t\x12#\n\npos_status\x18\x04 \x01(\x0e\x32\x0f.vxII.PosStatus\x12\x1f\n\x05pos3D\x18\x05 \x01(\x0b\x32\x10.vxII.Position3D\x12\x0f\n\x07heading\x18\x06 \x01(\x05\x12\r\n\x05speed\x18\x07 \x01(\x05\x12-\n\x08vehClass\x18\x08 \x01(\x0b\x32\x1b.vxII.VehicleClassification\x12\x1b\n\x04size\x18\t \x01(\x0b\x32\r.vxII.VehSize\x12,\n\x06lights\x18\n \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12,\n\x0b\x62rakeStatus\x18\x0b \x01(\x0b\x32\x17.vxII.BrakeSystemStatus\"F\n\x0cParticipants\x12\x0e\n\x06msgCnt\x18\x01 \x01(\r\x12&\n\x0bparticipant\x18\x02 \x03(\x0b\x32\x11.vxII.Participant*>\n\nObjectType\x12\x11\n\rOT_PEDESTRIAN\x10\x00\x12\x0f\n\x0bOT_NO_MOTOR\x10\x01\x12\x0c\n\x08OT_MOTOR\x10\x02*I\n\tPosStatus\x12\r\n\tPOS_ERROR\x10\x00\x12\x0c\n\x08POS_POOR\x10\x01\x12\x0c\n\x08POS_WELL\x10\x02\x12\x11\n\rPOS_EXCELLENT\x10\x03\x62\x06proto3')

_OBJECTTYPE = DESCRIPTOR.enum_types_by_name['ObjectType']
ObjectType = enum_type_wrapper.EnumTypeWrapper(_OBJECTTYPE)
_POSSTATUS = DESCRIPTOR.enum_types_by_name['PosStatus']
PosStatus = enum_type_wrapper.EnumTypeWrapper(_POSSTATUS)
OT_PEDESTRIAN = 0
OT_NO_MOTOR = 1
OT_MOTOR = 2
POS_ERROR = 0
POS_POOR = 1
POS_WELL = 2
POS_EXCELLENT = 3


_PARTICIPANT = DESCRIPTOR.message_types_by_name['Participant']
_PARTICIPANTS = DESCRIPTOR.message_types_by_name['Participants']
Participant = _reflection.GeneratedProtocolMessageType('Participant', (_message.Message,), {
  'DESCRIPTOR' : _PARTICIPANT,
  '__module__' : 'Participant_pb2'
  # @@protoc_insertion_point(class_scope:vxII.Participant)
  })
_sym_db.RegisterMessage(Participant)

Participants = _reflection.GeneratedProtocolMessageType('Participants', (_message.Message,), {
  'DESCRIPTOR' : _PARTICIPANTS,
  '__module__' : 'Participant_pb2'
  # @@protoc_insertion_point(class_scope:vxII.Participants)
  })
_sym_db.RegisterMessage(Participants)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTTYPE._serialized_start=511
  _OBJECTTYPE._serialized_end=573
  _POSSTATUS._serialized_start=575
  _POSSTATUS._serialized_end=648
  _PARTICIPANT._serialized_start=126
  _PARTICIPANT._serialized_end=437
  _PARTICIPANTS._serialized_start=439
  _PARTICIPANTS._serialized_end=509
# @@protoc_insertion_point(module_scope)
