# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PartptTrack.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VehBrake_pb2 as VehBrake__pb2
import DefPosition_pb2 as DefPosition__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PartptTrack.proto\x12\x04vxII\x1a\x0eVehBrake.proto\x1a\x11\x44\x65\x66Position.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9a\x02\n\x0bPartptTrack\x12\x0f\n\x07secMark\x18\x01 \x01(\r\x12\x1d\n\x03pos\x18\x02 \x01(\x0b\x32\x10.vxII.Position3D\x12\r\n\x05speed\x18\x03 \x01(\r\x12\x0f\n\x07heading\x18\x04 \x01(\r\x12\'\n\x06\x62rakes\x18\x0b \x01(\x0b\x32\x17.vxII.BrakeSystemStatus\x12\x0e\n\x06\x65vents\x18\x0c \x01(\r\x12+\n\x06lights\x18\r \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12*\n\x05horiz\x18\x0e \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12)\n\x04vert\x18\x0f \x01(\x0b\x32\x1b.google.protobuf.Int32Value*\x82\x01\n\x0b\x65SafeMsgLev\x12\x13\n\x0fIGNORE_SAFE_MSG\x10\x00\x12\x11\n\rINIT_SAFE_MSG\x10\x01\x12\x10\n\x0c\x46\x41R_SAFE_MSG\x10\x02\x12\x12\n\x0eGREEN_SAFE_MSG\x10\x03\x12\x13\n\x0fYELLOW_SAFE_MSG\x10\x04\x12\x10\n\x0cRED_SAFE_MSG\x10\x05*2\n\x0c\x65SafeMsgSour\x12\x10\n\x0c\x42SM_SAFE_MSG\x10\x00\x12\x10\n\x0cRSM_SAFE_MSG\x10\x01\x62\x06proto3')

_ESAFEMSGLEV = DESCRIPTOR.enum_types_by_name['eSafeMsgLev']
eSafeMsgLev = enum_type_wrapper.EnumTypeWrapper(_ESAFEMSGLEV)
_ESAFEMSGSOUR = DESCRIPTOR.enum_types_by_name['eSafeMsgSour']
eSafeMsgSour = enum_type_wrapper.EnumTypeWrapper(_ESAFEMSGSOUR)
IGNORE_SAFE_MSG = 0
INIT_SAFE_MSG = 1
FAR_SAFE_MSG = 2
GREEN_SAFE_MSG = 3
YELLOW_SAFE_MSG = 4
RED_SAFE_MSG = 5
BSM_SAFE_MSG = 0
RSM_SAFE_MSG = 1


_PARTPTTRACK = DESCRIPTOR.message_types_by_name['PartptTrack']
PartptTrack = _reflection.GeneratedProtocolMessageType('PartptTrack', (_message.Message,), {
  'DESCRIPTOR' : _PARTPTTRACK,
  '__module__' : 'PartptTrack_pb2'
  # @@protoc_insertion_point(class_scope:vxII.PartptTrack)
  })
_sym_db.RegisterMessage(PartptTrack)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ESAFEMSGLEV._serialized_start=380
  _ESAFEMSGLEV._serialized_end=510
  _ESAFEMSGSOUR._serialized_start=512
  _ESAFEMSGSOUR._serialized_end=562
  _PARTPTTRACK._serialized_start=95
  _PARTPTTRACK._serialized_end=377
# @@protoc_insertion_point(module_scope)
