# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RSM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VehSize_pb2 as VehSize__pb2
import VehClass_pb2 as VehClass__pb2
import DefMotion_pb2 as DefMotion__pb2
import VehStatus_pb2 as VehStatus__pb2
import DefPosition_pb2 as DefPosition__pb2
import DefAcceleration_pb2 as DefAcceleration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tRSM.proto\x12\x04vxII\x1a\rVehSize.proto\x1a\x0eVehClass.proto\x1a\x0f\x44\x65\x66Motion.proto\x1a\x0fVehStatus.proto\x1a\x11\x44\x65\x66Position.proto\x1a\x15\x44\x65\x66\x41\x63\x63\x65leration.proto\"\xe4\x03\n\x0fParticipantData\x12\'\n\x08ptc_type\x18\x01 \x01(\x0e\x32\x15.vxII.ParticipantType\x12\r\n\x05ptcId\x18\x02 \x01(\r\x12 \n\x06source\x18\x03 \x01(\x0e\x32\x10.vxII.SourceType\x12\n\n\x02id\x18\x04 \x01(\t\x12\x0f\n\x07secMark\x18\x05 \x01(\r\x12\x1d\n\x03pos\x18\x06 \x01(\x0b\x32\x10.vxII.Position3D\x12\x32\n\rposConfidence\x18\x07 \x01(\x0b\x32\x1b.vxII.PositionConfidenceSet\x12-\n\x0ctransmission\x18\x08 \x01(\x0e\x32\x17.vxII.TransmissionState\x12\r\n\x05speed\x18\t \x01(\r\x12\x0f\n\x07heading\x18\n \x01(\r\x12\r\n\x05\x61ngle\x18\x0b \x01(\x05\x12,\n\tmotionCfd\x18\x0c \x01(\x0b\x32\x19.vxII.MotionConfidenceSet\x12+\n\x08\x61\x63\x63\x65lSet\x18\r \x01(\x0b\x32\x19.vxII.AccelerationSet4Way\x12\x1b\n\x04size\x18\x0e \x01(\x0b\x32\r.vxII.VehSize\x12\x31\n\x0cvehicleClass\x18\x0f \x01(\x0b\x32\x1b.vxII.VehicleClassification\"\x82\x01\n\x15RoadsideSafetyMessage\x12\x0e\n\x06msgCnt\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\t\x12 \n\x06refPos\x18\x03 \x01(\x0b\x32\x10.vxII.Position3D\x12+\n\x0cparticipants\x18\x04 \x03(\x0b\x32\x15.vxII.ParticipantData*\xa6\x01\n\x0fParticipantType\x12\x1c\n\x18unknown_participant_type\x10\x00\x12\x1a\n\x16motor_participant_type\x10\x01\x12\x1e\n\x1anon_motor_participant_type\x10\x02\x12\x1f\n\x1bpedestrian_participant_type\x10\x03\x12\x18\n\x14rsu_participant_type\x10\x04*\xd4\x01\n\nSourceType\x12\x17\n\x13unknown_source_type\x10\x00\x12\x18\n\x14selfinfo_source_type\x10\x01\x12\x13\n\x0fv2x_source_type\x10\x02\x12\x15\n\x11video_source_type\x10\x03\x12\x1e\n\x1amicrowaveRadar_source_type\x10\x04\x12\x14\n\x10loop_source_type\x10\x05\x12\x15\n\x11lidar_source_type\x10\x06\x12\x1a\n\x16integrated_source_type\x10\x07\x62\x06proto3')

_PARTICIPANTTYPE = DESCRIPTOR.enum_types_by_name['ParticipantType']
ParticipantType = enum_type_wrapper.EnumTypeWrapper(_PARTICIPANTTYPE)
_SOURCETYPE = DESCRIPTOR.enum_types_by_name['SourceType']
SourceType = enum_type_wrapper.EnumTypeWrapper(_SOURCETYPE)
unknown_participant_type = 0
motor_participant_type = 1
non_motor_participant_type = 2
pedestrian_participant_type = 3
rsu_participant_type = 4
unknown_source_type = 0
selfinfo_source_type = 1
v2x_source_type = 2
video_source_type = 3
microwaveRadar_source_type = 4
loop_source_type = 5
lidar_source_type = 6
integrated_source_type = 7


_PARTICIPANTDATA = DESCRIPTOR.message_types_by_name['ParticipantData']
_ROADSIDESAFETYMESSAGE = DESCRIPTOR.message_types_by_name['RoadsideSafetyMessage']
ParticipantData = _reflection.GeneratedProtocolMessageType('ParticipantData', (_message.Message,), {
  'DESCRIPTOR' : _PARTICIPANTDATA,
  '__module__' : 'RSM_pb2'
  # @@protoc_insertion_point(class_scope:vxII.ParticipantData)
  })
_sym_db.RegisterMessage(ParticipantData)

RoadsideSafetyMessage = _reflection.GeneratedProtocolMessageType('RoadsideSafetyMessage', (_message.Message,), {
  'DESCRIPTOR' : _ROADSIDESAFETYMESSAGE,
  '__module__' : 'RSM_pb2'
  # @@protoc_insertion_point(class_scope:vxII.RoadsideSafetyMessage)
  })
_sym_db.RegisterMessage(RoadsideSafetyMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARTICIPANTTYPE._serialized_start=747
  _PARTICIPANTTYPE._serialized_end=913
  _SOURCETYPE._serialized_start=916
  _SOURCETYPE._serialized_end=1128
  _PARTICIPANTDATA._serialized_start=127
  _PARTICIPANTDATA._serialized_end=611
  _ROADSIDESAFETYMESSAGE._serialized_start=614
  _ROADSIDESAFETYMESSAGE._serialized_end=744
# @@protoc_insertion_point(module_scope)
